export const DEFAULT_PAGE_LIMIT = 10;
export const DATE_REGEX = new RegExp('(0[1-9]|1[0-9]|2[0-9]|3[0-1])(-|\\.|\\/)(0[1-9]|[12]\\d|3[01])(-|\\.|\\/)([12]\\d{3})');
export const REVERT_DATE_REGEX = new RegExp('([12]\\d{3})(-|\\.|\\/)(0[1-9]|[12]\\d|3[01])(-|\\.|\\/)(0[1-9]|1[0-9]|2[0-9]|3[0-1])');
export const MAX_IMAGE_SIZE = 10240; //kb
export const DEFAULT_CAR_IMG = '/images/car.png';
export const DEFAULT_PROFILE_IMG = '/images/profile_man.png';
export const DEFAULT_PROFILE_WOMAN_IMG = '/images/profile_woman.png';
export const DEFAULT_PROFILE_BACKGROUND = '/images/background.jpg';
export const PDF_IMG = '/public/images/pdf.png';
export const EXCEL_IMG = '/public/images/excel.png';
export const WORD_IMG = '/public/images/word.png';
export const POWER_POINT_IMG = '/public/images/power_point.png';
export const VIDEO_IMG = '/public/images/video.png';
export const DEFAULT_FILE_IMG = '/public/images/file_unknown.png';